const KEY="AF_ERP_COMPLETE_V2";
const seed={orders:[],customers:[],products:[],suppliers:[],expenses:[],payments:[],accounts:[],settings:{name:"Al Furqun",currency:"৳",notify:true}};
let db=read();let page="dashboard";
function read(){try{return Object.assign({},seed,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return JSON.parse(JSON.stringify(seed))}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function id(p){return p+"-"+Date.now().toString(36).toUpperCase()}
function esc(v){return String(v??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[x]))}
function money(n){return `${db.settings.currency||"৳"} ${Number(n||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function today(){return new Date().toISOString().slice(0,10)}
function sales(o){return +o.salePrice*(+o.quantity||0)}
function cost(o){return (+o.buyPrice*(+o.quantity||0))+ (+o.shipping||0)+(+o.advanced||0)+(+o.packingCharge||0)+(+o.deliveryCharge||0)+(+o.courierCharge||0)+(+o.codReturn||0)}
function profit(o){return sales(o)-cost(o)-(+o.deliveryCharge||0)}
function toast(msg,ok=true){let r=document.getElementById("toast"),e=document.createElement("div");e.className="toast";e.innerHTML=`<i>${ok?"✓":"!"}</i><div><b>${ok?"Successful":"Notice"}</b><div class="muted">${esc(msg)}</div></div>`;r.appendChild(e);setTimeout(()=>e.remove(),2700)}
function badge(s){let c=["Delivered","Completed"].includes(s)?"green":["Returned","Cancelled"].includes(s)?"red":s==="Pending"?"yellow":"blue";return `<span class="badge ${c}">${esc(s||"Pending")}</span>`}
function nav(){document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===page))}
function render(){document.getElementById("login").classList.add("hidden");document.getElementById("app").classList.remove("hidden");nav();let fn={dashboard,orders,customers,products,suppliers,stockreport,expenses,accounts,reports,settings}[page];document.getElementById("content").innerHTML=fn();bind()}
function head(t,s,a=""){return `<div class="title"><div><h2>${t}</h2><div class="muted">${s}</div></div><div class="actions">${a}</div></div>`}
function dashboard(){
 let total=db.orders.reduce((a,o)=>a+sales(o),0),pf=db.orders.filter(o=>!["Returned","Cancelled"].includes(o.status)).reduce((a,o)=>a+profit(o),0),loss=db.orders.filter(o=>["Returned","Cancelled"].includes(o.status)).reduce((a,o)=>a+Math.abs(profit(o)),0);
 let pts=[0,1,2,3,4,5,6].map(i=>{let d=new Date();d.setDate(d.getDate()-6+i);let x=d.toISOString().slice(0,10);return db.orders.filter(o=>o.date===x).reduce((a,o)=>a+sales(o),0)}),mx=Math.max(...pts,1),poly=pts.map((v,i)=>`${i*100/6},${190-v/mx*160}`).join(" ");
 let recent=[...db.orders].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,7);
 return `<div class="page">${head("Dashboard","Everything important about Al Furqun in one place.")}<div class="stats">
 <div class="stat" onclick="page='orders';render()"><label>Total Sales</label><strong>${money(total)}</strong><span class="green">↗ ${db.orders.length} orders</span></div>
 <div class="stat" onclick="page='orders';render()"><label>Total Amount</label><strong>${money(total)}</strong><span class="blue">All order value</span></div>
 <div class="stat" onclick="page='reports';render()"><label>Total Profit</label><strong>${money(pf)}</strong><span class="green">Calculated profit</span></div>
 <div class="stat" onclick="page='reports';render()"><label>Total Loss</label><strong>${money(loss)}</strong><span class="red">Returns / cancellations</span></div></div>
 <div class="grid2"><div class="card"><div class="card-head"><h3>Sales Overview</h3><span class="muted">Last 7 days</span></div><div class="chart"><svg viewBox="0 0 100 200" preserveAspectRatio="none"><polyline points="0,190 100,190" stroke="#e9edf3" fill="none"/><polygon points="${poly} 100,200 0,200" fill="#2563eb" opacity=".08"/><polyline points="${poly}" fill="none" stroke="#2563eb" stroke-width="2" vector-effect="non-scaling-stroke"/></svg></div></div>
 <div class="card"><div class="card-head"><h3>Business Overview</h3></div><div class="summary"><div><small>Customers</small><strong>${db.customers.length}</strong></div><div><small>Products</small><strong>${db.products.length}</strong></div><div><small>Suppliers</small><strong>${db.suppliers.length}</strong></div><div><small>Expenses</small><strong>${money(db.expenses.reduce((a,x)=>a+ +x.amount,0))}</strong></div></div><div class="empty" style="padding:20px">Your ERP is ready for data.</div></div></div>
 <div class="card" style="margin-top:14px"><div class="card-head"><h3>Recent Orders</h3><button class="btn" onclick="page='orders';render()">View All</button></div>${recent.length?orderTable(recent):empty("No orders yet. Add your first order.")}</div></div>`
}
function empty(x){return `<div class="empty">${esc(x)}</div>`}
function orderTable(rows){return `<div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Product</th><th>Date</th><th>Total</th><th>Profit</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.customerName)}</td><td>${esc(o.productName)}</td><td>${esc(o.date)}</td><td>${money(sales(o))}</td><td>${money(profit(o))}</td><td>${badge(o.status)}</td><td><button class="btn" onclick="viewOrder('${o.id}')">View</button></td></tr>`).join("")}</tbody></table></div>`}
function orders(){let rows=[...db.orders].sort((a,b)=>b.date.localeCompare(a.date));return `<div class="page">${head("Orders","Create, edit and track every customer order.",`<button class="btn primary" onclick="orderModal()">+ Add New Customer</button>`)}<div class="card">${rows.length?orderTable(rows):empty("No orders yet.")}</div></div>`}
function customers(){let q=(document.getElementById("search")?.value||"").toLowerCase().trim();let list=db.customers.filter(c=>!q||[c.name,c.phone,c.address].some(v=>String(v||"").toLowerCase().includes(q)));return `<div class="page">${head("Customers","Search customer history, contact details and order totals.",`<button class="btn primary" onclick="orderModal()">+ Add Customer</button>`)}<div class="card"><div class="field search-local"><label>Search Customer</label><input id="customerSearch" placeholder="Name or phone..." value="${esc(q)}"></div>${list.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Phone</th><th>Orders</th><th>Sales</th><th>Last Order</th><th>Actions</th></tr></thead><tbody>${list.map(c=>{let os=db.orders.filter(o=>o.customerId===c.id);return `<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.phone)}</td><td>${os.length}</td><td>${money(os.reduce((a,o)=>a+sales(o),0))}</td><td>${os.sort((a,b)=>b.date.localeCompare(a.date))[0]?.date||"-"}</td><td><button class="btn" onclick="customerView('${c.id}')">History</button> <button class="btn" onclick="customerEdit('${c.id}')">Edit</button> <button class="btn danger" onclick="customerDelete('${c.id}')">Delete</button></td></tr>`}).join("")}</tbody></table></div>`:empty("No matching customers.")}</div></div>`}
function products(){let q=(document.getElementById("search")?.value||"").toLowerCase().trim();let list=db.products.filter(p=>!q||[p.name,db.suppliers.find(s=>s.id===p.supplierId)?.name].some(v=>String(v||"").toLowerCase().includes(q)));return `<div class="page">${head("Products","Search products, buy price, supplier and stock.",`<button class="btn primary" onclick="productModal()">+ Add Product</button>`)}<div class="card"><div class="field search-local"><label>Search Product</label><input id="productSearch" placeholder="Product or supplier..." value="${esc(q)}"></div>${list.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>Buy Price</th><th>Supplier</th><th>Stock</th><th>Reorder</th><th>Actions</th></tr></thead><tbody>${list.map(p=>`<tr><td><b>${esc(p.name)}</b></td><td>${money(p.buyPrice)}</td><td>${esc(db.suppliers.find(s=>s.id===p.supplierId)?.name||"-")}</td><td>${p.stock}</td><td>${p.reorder}</td><td><button class="btn" onclick="productModal('${p.id}')">Edit</button> <button class="btn danger" onclick="productDelete('${p.id}')">Delete</button></td></tr>`).join("")}</tbody></table></div>`:empty("No matching products.")}</div></div>`}
function suppliers(){return `<div class="page">${head("Suppliers","Supplier contacts, links and payment records.",`<button class="btn primary" onclick="supplierModal()">+ Add Supplier</button>`)}<div class="card">${db.suppliers.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>WhatsApp</th><th>Link</th><th>Products</th><th>Actions</th></tr></thead><tbody>${db.suppliers.map(s=>`<tr><td><b>${esc(s.name)}</b></td><td>${esc(s.whatsapp||"-")}</td><td>${s.link?`<a href="${esc(s.link)}" target="_blank">Open</a>`:"-"}</td><td>${db.products.filter(p=>p.supplierId===s.id).length}</td><td><button class="btn" onclick="supplierModal('${s.id}')">Edit</button> <button class="btn danger" onclick="supplierDelete('${s.id}')">Delete</button></td></tr>`).join("")}</tbody></table></div>`:empty("No suppliers yet.")}</div></div>`}
function stockreport(){return `<div class="page">${head("Stock Report","Stock, profit/loss and customer reports with separate print buttons.",`<button class="btn primary" onclick="printReport('stockReportPrint')">Print Stock</button><button class="btn" onclick="printReport('profitReportPrint')">Print Profit & Loss</button><button class="btn" onclick="printReport('customerReportPrint')">Print Customers</button>`)}<div class="card" id="stockReportPrint"><div class="card-head"><h3>Stock Report</h3><span class="muted">Current inventory</span></div>${db.products.length?`<table class="table"><thead><tr><th>Product</th><th>Supplier</th><th>Stock</th><th>Buy Price</th><th>Stock Value</th><th>Status</th></tr></thead><tbody>${db.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(db.suppliers.find(s=>s.id===p.supplierId)?.name||"-")}</td><td>${p.stock}</td><td>${money(p.buyPrice)}</td><td>${money((+p.stock||0)*(+p.buyPrice||0))}</td><td>${+p.stock<=+p.reorder?'<span class="badge red">Low Stock</span>':'<span class="badge green">In Stock</span>'}</td></tr>`).join("")}</tbody></table>`:empty("No products yet.")}</div><div class="card" id="profitReportPrint" style="margin-top:14px"><div class="card-head"><h3>Profit & Loss Report</h3></div>${profitLossReport()}</div><div class="card" id="customerReportPrint" style="margin-top:14px"><div class="card-head"><h3>Customer Report</h3></div>${customerReport()}</div></div>`}
function profitLossReport(){let salesTotal=db.orders.reduce((a,o)=>a+sales(o),0),gross=db.orders.reduce((a,o)=>a+profit(o),0),exp=db.expenses.reduce((a,x)=>a+ +x.amount,0),net=gross-exp;return `<div class="summary"><div><small>Total Sales</small><strong>${money(salesTotal)}</strong></div><div><small>Gross Profit</small><strong>${money(gross)}</strong></div><div><small>Expenses</small><strong>${money(exp)}</strong></div><div><small>Net ${net>=0?'Profit':'Loss'}</small><strong class="${net>=0?'green':'red'}">${money(Math.abs(net))}</strong></div></div>`}
function customerReport(){return db.customers.length?`<table class="table"><thead><tr><th>Customer</th><th>Phone</th><th>Orders</th><th>Sales</th><th>Profit</th></tr></thead><tbody>${db.customers.map(c=>{let os=db.orders.filter(o=>o.customerId===c.id);return `<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${os.length}</td><td>${money(os.reduce((a,o)=>a+sales(o),0))}</td><td>${money(os.reduce((a,o)=>a+profit(o),0))}</td></tr>`}).join("")}</tbody></table>`:empty("No customers yet.")}
function printReport(idv){let node=document.getElementById(idv);if(!node)return;let w=window.open("","_blank");w.document.write(`<html><head><title>Al Furqun Report</title><style>body{font-family:Poppins,Arial;padding:25px;color:#172033}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:9px;border-bottom:1px solid #ddd;text-align:left;font-size:11px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.summary>div{padding:10px;background:#f6f8fc}.summary small{display:block;color:#667085}.summary strong{font-size:14px}.badge{padding:4px 8px;border-radius:15px}</style></head><body><h2>Al Furqun</h2>${node.innerHTML}</body></html>`);w.document.close();w.print()}
function expenses(){return `<div class="page">${head("Expenses","Record business expenses and keep net profit realistic.",`<button class="btn primary" onclick="expenseModal()">+ Add Expense</button>`)}<div class="card"><div class="summary"><div><small>Total Expenses</small><strong>${money(db.expenses.reduce((a,x)=>a+ +x.amount,0))}</strong></div><div><small>Records</small><strong>${db.expenses.length}</strong></div></div>${db.expenses.length?`<table class="table"><thead><tr><th>Date</th><th>Category</th><th>Amount</th><th>Note</th><th></th></tr></thead><tbody>${db.expenses.map(x=>`<tr><td>${x.date}</td><td>${esc(x.category)}</td><td>${money(x.amount)}</td><td>${esc(x.note||"-")}</td><td><button class="btn danger" onclick="expenseDelete('${x.id}')">Delete</button></td></tr>`).join("")}</tbody></table>`:empty("No expenses recorded.")}</div></div>`}
function accounts(){let total=db.payments.reduce((a,p)=>a+ +p.amount,0);return `<div class="page">${head("Accounts","Supplier payments and your own payment accounts.",`<button class="btn primary" onclick="paymentModal()">+ Supplier Payment</button><button class="btn" onclick="accountModal()">+ My Account</button>`)}<div class="grid3"><div class="mini"><h4>Total Supplier Payments</h4><strong>${money(total)}</strong></div><div class="mini"><h4>bKash / Nagad</h4><strong>${money(db.payments.filter(p=>p.method!=="Bank").reduce((a,p)=>a+ +p.amount,0))}</strong></div><div class="mini"><h4>Bank</h4><strong>${money(db.payments.filter(p=>p.method==="Bank").reduce((a,p)=>a+ +p.amount,0))}</strong></div></div><div class="card" style="margin-top:14px"><h3>Payment History</h3>${db.payments.length?`<table class="table"><thead><tr><th>Date</th><th>Supplier</th><th>Method</th><th>Amount</th><th>Note</th></tr></thead><tbody>${db.payments.map(p=>`<tr><td>${p.date}</td><td>${esc(db.suppliers.find(s=>s.id===p.supplierId)?.name||"-")}</td><td>${p.method}</td><td>${money(p.amount)}</td><td>${esc(p.note||"-")}</td></tr>`).join("")}</tbody></table>`:empty("No supplier payments yet.")}</div><div class="card" style="margin-top:14px"><h3>My Accounts</h3><div class="grid3">${db.accounts.map(a=>`<div class="mini"><h4>${esc(a.type)}</h4><strong style="font-size:13px">${esc(a.number)}</strong><p class="muted">${esc(a.name||"")}</p></div>`).join("")||empty("Add your Bank, bKash or Nagad account.")}</div></div></div>`}
function reports(){return `<div class="page">${head("Reports","Stock, sales, profit/loss and customer reports with separate print buttons.")}<div class="tabs"><button class="tab active" onclick="report('stock',this)">Stock Report</button><button class="tab" onclick="report('sales',this)">Sales Report</button><button class="tab" onclick="report('profit',this)">Profit & Loss</button><button class="tab" onclick="report('customers',this)">Customer Report</button><button class="tab" onclick="report('products',this)">Product Report</button><button class="tab" onclick="report('expenses',this)">Expense Report</button></div><div id="reportBox" class="card">${stockReport()}</div></div>`}
function printReport(title,html){let w=window.open("","_blank");w.document.write(`<html><head><title>${title} - Al Furqun</title><style>body{font-family:Poppins,Arial;padding:28px;color:#172033}h1{font-size:22px}.muted{color:#667085;font-size:11px}.table{width:100%;border-collapse:collapse;margin-top:18px}.table th,.table td{padding:9px;border-bottom:1px solid #ddd;text-align:left;font-size:11px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.summary>div{padding:12px;background:#f5f7fa;border-radius:8px}.summary small{display:block;color:#667085}.summary strong{font-size:14px}</style></head><body><h1>Al Furqun — ${title}</h1><div class="muted">Generated: ${today()}</div>${html}<script>window.onload=()=>window.print()</script></body></html>`);w.document.close()}
function stockReport(){return `<h3>Stock Report</h3><table class="table"><thead><tr><th>Product</th><th>Supplier</th><th>Stock</th><th>Buy Price</th><th>Stock Value</th><th>Status</th></tr></thead><tbody>${db.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(db.suppliers.find(s=>s.id===p.supplierId)?.name||"-")}</td><td>${p.stock}</td><td>${money(p.buyPrice)}</td><td>${money((+p.stock||0)*(+p.buyPrice||0))}</td><td>${+p.stock<=+p.reorder?"Low Stock":"In Stock"}</td></tr>`).join("")}</tbody></table><button class="btn primary no-print" onclick="printReport('Stock Report',document.getElementById('reportBox').innerHTML)">Print Stock Report</button>`}
function salesReport(){return `<h3>Sales Report</h3>${db.orders.length?orderTable(db.orders):empty("No sales data.")}<button class="btn primary no-print" onclick="printReport('Sales Report',document.getElementById('reportBox').innerHTML)">Print Sales Report</button>`}
function profitReport(){let gross=db.orders.reduce((a,o)=>a+profit(o),0),ex=db.expenses.reduce((a,x)=>a+ +x.amount,0),net=gross-ex;return `<h3>Profit & Loss Report</h3><div class="summary"><div><small>Sales</small><strong>${money(db.orders.reduce((a,o)=>a+sales(o),0))}</strong></div><div><small>Gross Profit</small><strong>${money(gross)}</strong></div><div><small>Expenses</small><strong>${money(ex)}</strong></div><div><small>Net Profit / Loss</small><strong class="${net>=0?'green':'red'}">${money(net)}</strong></div></div><button class="btn primary no-print" onclick="printReport('Profit & Loss Report',document.getElementById('reportBox').innerHTML)">Print Profit & Loss</button>`}
function customerReport(){return `<h3>Customer Report</h3><table class="table"><thead><tr><th>Customer</th><th>Phone</th><th>Orders</th><th>Sales</th><th>Profit</th></tr></thead><tbody>${db.customers.map(c=>{let os=db.orders.filter(o=>o.customerId===c.id);return `<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${os.length}</td><td>${money(os.reduce((a,o)=>a+sales(o),0))}</td><td>${money(os.reduce((a,o)=>a+profit(o),0))}</td></tr>`}).join("")}</tbody></table><button class="btn primary no-print" onclick="printReport('Customer Report',document.getElementById('reportBox').innerHTML)">Print Customer Report</button>`}
function productReport(){return `<h3>Product Report</h3><table class="table"><thead><tr><th>Product</th><th>Units Sold</th><th>Sales</th><th>Profit</th></tr></thead><tbody>${db.products.map(p=>{let os=db.orders.filter(o=>o.productId===p.id);return `<tr><td>${esc(p.name)}</td><td>${os.reduce((a,o)=>a+ +o.quantity,0)}</td><td>${money(os.reduce((a,o)=>a+sales(o),0))}</td><td>${money(os.reduce((a,o)=>a+profit(o),0))}</td></tr>`}).join("")}</tbody></table><button class="btn primary no-print" onclick="printReport('Product Report',document.getElementById('reportBox').innerHTML)">Print Product Report</button>`}
function expenseReport(){return `<h3>Expense Report</h3><table class="table"><thead><tr><th>Date</th><th>Category</th><th>Amount</th><th>Note</th></tr></thead><tbody>${db.expenses.map(x=>`<tr><td>${x.date}</td><td>${esc(x.category)}</td><td>${money(x.amount)}</td><td>${esc(x.note||"-")}</td></tr>`).join("")}</tbody></table><button class="btn primary no-print" onclick="printReport('Expense Report',document.getElementById('reportBox').innerHTML)">Print Expense Report</button>`}
function report(t,b){document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById("reportBox").innerHTML=t==="stock"?stockReport():t==="sales"?salesReport():t==="profit"?profitReport():t==="customers"?customerReport():t==="products"?productReport():expenseReport()}
function settings(){return `<div class="page">${head("Settings","Business and data settings.",`<button class="btn primary" onclick="saveSettings()">Save</button>`)}<div class="card"><div class="form-grid"><div class="field"><label>Business Name</label><input id="sname" value="${esc(db.settings.name)}"></div><div class="field"><label>Currency</label><input id="scurrency" value="${esc(db.settings.currency)}"></div></div><div class="setting"><div><b>Success notifications</b><div class="muted">Show success box after adding/editing data.</div></div><div id="toggle" class="toggle ${db.settings.notify?"on":""}" onclick="this.classList.toggle('on')"></div></div><div class="setting"><div><b>Export Backup</b><div class="muted">Download all ERP data as JSON.</div></div><button class="btn" onclick="backup()">Export Backup</button></div><div class="setting"><div><b>Reset Local Data</b><div class="muted">Deletes all data saved in this browser.</div></div><button class="btn danger" onclick="resetAll()">Reset</button></div></div></div>`}
function suppliersOptions(){return `<option value="">Select supplier</option>${db.suppliers.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}`}
function productsOptions(){return `<option value="">Select product</option>${db.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("")}`}
function openModal(body){document.getElementById("modal").innerHTML=`<div class="modal-bg"><div class="modal-box">${body}</div></div>`}
function closeModal(){document.getElementById("modal").innerHTML=""}
function orderModal(existing=null){
 let o=existing||{id:id("ORD"),date:today(),source:"Marketplace",status:"Pending",quantity:1,shipping:0,advanced:0,currentPrice:0};
 openModal(`<div class="modal-head"><div><h3>${existing?"Edit Order":"Add New Customer / Order"}</h3><div class="muted">Products and suppliers added in their own sections automatically appear here.</div></div><button class="close" onclick="closeModal()">×</button></div>
 <form id="orderForm"><div class="form-grid three">
 <div class="field"><label>Date</label><input name="date" type="date" value="${o.date}" required></div><div class="field"><label>Order ID</label><input name="id" value="${esc(o.id)}" required></div><div class="field"><label>Source</label><select name="source">${["Marketplace","Whatsapp","Messenger","Tiktok","Phone"].map(x=>`<option ${o.source===x?"selected":""}>${x}</option>`).join("")}</select></div>
 <div class="field"><label>Customer Name</label><input name="customerName" value="${esc(o.customerName||"")}" required></div><div class="field"><label>Phone</label><input name="phone" value="${esc(o.phone||"")}" required></div><div class="field fullrow"><label>Address</label><textarea name="address" required>${esc(o.address||"")}</textarea></div>
 <div class="field"><label>Product</label><select name="productId" id="op">${productsOptions()}</select></div><div class="field"><label>Quantity</label><input name="quantity" id="qty" type="number" min="1" value="${o.quantity||1}"></div><div class="field"><label>Sell* / Unit</label><input name="salePrice" id="sale" type="number" step=".01" value="${o.salePrice||0}"></div>
 <div class="field"><label>Buy* / Unit</label><input name="buyPrice" id="buy" type="number" step=".01" value="${o.buyPrice||0}"></div><div class="field"><label>Shipping*</label><input name="shipping" id="shipping" type="number" step=".01" value="${o.shipping||0}"></div><div class="field"><label>Advanced*</label><input name="advanced" id="advanced" type="number" step=".01" value="${o.advanced||0}"></div>
 <div class="field"><label>Current</label><input name="currentPrice" id="current" type="number" step=".01" value="${o.currentPrice||0}"></div><div class="field"><label>Packaging</label><input name="packingCharge" id="pack" type="number" step=".01" value="${o.packingCharge||0}"></div><div class="field"><label>Delivery Charge</label><input name="deliveryCharge" id="delivery" type="number" step=".01" value="${o.deliveryCharge||0}"></div>
 <div class="field"><label>COD / Return</label><input name="codReturn" id="cod" type="number" step=".01" value="${o.codReturn||0}"></div><div class="field"><label>Courier Charge</label><input name="courierCharge" id="courierCharge" type="number" step=".01" value="${o.courierCharge||0}"></div><div class="field"><label>Supplier</label><select name="supplierId" id="osupplier">${suppliersOptions()}</select></div>
 <div class="field"><label>Courier</label><select name="courier"><option>Pathao</option><option>Steadfast</option></select></div><div class="field"><label>Tracking Link</label><input name="trackingLink" type="url" value="${esc(o.trackingLink||"")}"></div><div class="field"><label>Status</label><select name="status">${["Pending","Confirmed","Shipped","Delivered","Completed","Returned","Cancelled"].map(x=>`<option ${o.status===x?"selected":""}>${x}</option>`).join("")}</select></div>
 </div>
 <div class="calc-card"><div class="calc-title">Calculations <span>Live</span></div><div class="calc-grid"><div><label>Payable</label><strong id="calcPayable">৳ 0.00</strong></div><div><label>Profit / Loss</label><strong id="calcProfit">৳ 0.00</strong></div><div><label>Receivable</label><strong id="calcReceivable">৳ 0.00</strong></div></div><div class="calc-note">Profit/Loss = sales − product cost − shipping − advanced − packaging − courier charge − COD/return. Receivable = customer total − advanced.</div></div>
 <div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Cancel</button><button class="btn primary">${existing?"Update":"Save Customer & Order"}</button></div></form>`);
 document.querySelector("#op").value=o.productId||"";document.querySelector("#osupplier").value=o.supplierId||"";document.querySelector("[name=courier]").value=o.courier||"Pathao";
 function calc(){const q=+document.getElementById("qty").value||0,buy=+document.getElementById("buy").value||0,sell=+document.getElementById("sale").value||0,shipping=+shippingEl.value||0,advanced=+advancedEl.value||0,pack=+packEl.value||0,delivery=+deliveryEl.value||0,cod=+codEl.value||0,courier=+courierEl.value||0;const productCost=buy*q,totalCost=productCost+shipping+advanced+pack+courier+cod,pl=sell*q-totalCost,payable=totalCost,receivable=sell*q+delivery+cod-advanced;document.getElementById("calcPayable").textContent=money(payable);document.getElementById("calcProfit").textContent=money(pl);document.getElementById("calcProfit").className=pl>=0?"calc-positive":"calc-negative";document.getElementById("calcReceivable").textContent=money(receivable)}
 const shippingEl=document.getElementById("shipping"),advancedEl=document.getElementById("advanced"),packEl=document.getElementById("pack"),deliveryEl=document.getElementById("delivery"),codEl=document.getElementById("cod"),courierEl=document.getElementById("courierCharge");
 document.getElementById("op").onchange=()=>{let p=db.products.find(x=>x.id===document.getElementById("op").value);if(p){document.getElementById("buy").value=p.buyPrice;document.getElementById("current").value=p.buyPrice;document.getElementById("sale").value=p.sellPrice||document.getElementById("sale").value;document.getElementById("osupplier").value=p.supplierId||""}calc()};
 ["qty","sale","buy","shipping","advanced","current","pack","delivery","cod","courierCharge"].forEach(x=>document.getElementById(x).addEventListener("input",calc));calc();
 document.getElementById("orderForm").onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));["quantity","salePrice","buyPrice","shipping","advanced","currentPrice","deliveryCharge","packingCharge","codReturn","courierCharge"].forEach(k=>d[k]=+d[k]||0);d.productName=db.products.find(p=>p.id===d.productId)?.name||"Custom Product";d.customerId=existing?.customerId||id("CUS");if(existing){let i=db.orders.findIndex(x=>x.id===existing.id);db.orders[i]=d;let c=db.customers.findIndex(x=>x.id===d.customerId);if(c>=0)db.customers[c]={...db.customers[c],name:d.customerName,phone:d.phone,address:d.address}}else{db.customers.push({id:d.customerId,name:d.customerName,phone:d.phone,address:d.address});db.orders.push(d);let p=db.products.find(x=>x.id===d.productId);if(p)p.stock=Math.max(0,(+p.stock||0)-d.quantity)}save();closeModal();toast(existing?"Order updated successfully.":"Customer and order added successfully.");render()}
}
function productModal(pid=null){let p=pid?db.products.find(x=>x.id===pid):{name:"",buyPrice:0,supplierId:"",stock:0,reorder:2};openModal(`<div class="modal-head"><h3>${pid?"Edit Product":"Add Product"}</h3><button class="close" onclick="closeModal()">×</button></div><form id="productForm"><div class="form-grid"><div class="field"><label>Product Name</label><input name="name" value="${esc(p.name)}" required></div><div class="field"><label>Current Price</label><input name="currentPrice" type="number" step=".01" value="${p.currentPrice||p.buyPrice||0}"></div><div class="field"><label>Buy Price</label><input name="buyPrice" type="number" step=".01" value="${p.buyPrice}" required></div><div class="field"><label>Sell Price</label><input name="sellPrice" type="number" step=".01" value="${p.sellPrice||0}"></div><div class="field"><label>Supplier</label><select name="supplierId">${suppliersOptions()}</select></div><div class="field"><label>Opening Stock</label><input name="stock" type="number" value="${p.stock}"></div><div class="field"><label>Reorder Level</label><input name="reorder" type="number" value="${p.reorder}"></div></div><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Cancel</button><button class="btn primary">Save Product</button></div></form>`);document.querySelector("#productForm [name=supplierId]").value=p.supplierId||"";document.getElementById("productForm").onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));d.currentPrice=+d.currentPrice||0;d.buyPrice=+d.buyPrice;d.sellPrice=+d.sellPrice||0;d.stock=+d.stock;d.reorder=+d.reorder;if(pid)Object.assign(p,d);else db.products.push({id:id("PRD"),...d});save();closeModal();toast(pid?"Product updated successfully.":"Product added successfully.");render()}}
function supplierModal(sid=null){let s=sid?db.suppliers.find(x=>x.id===sid):{name:"",whatsapp:"",link:""};openModal(`<div class="modal-head"><h3>${sid?"Edit Supplier":"Add Supplier"}</h3><button class="close" onclick="closeModal()">×</button></div><form id="supplierForm"><div class="form-grid"><div class="field"><label>Supplier Name</label><input name="name" value="${esc(s.name)}" required></div><div class="field"><label>WhatsApp Number</label><input name="whatsapp" value="${esc(s.whatsapp||"")}"></div><div class="field fullrow"><label>Any Link</label><input name="link" type="url" value="${esc(s.link||"")}"></div></div><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Cancel</button><button class="btn primary">Save Supplier</button></div></form>`);document.getElementById("supplierForm").onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));if(sid)Object.assign(s,d);else db.suppliers.push({id:id("SUP"),...d});save();closeModal();toast(sid?"Supplier updated successfully.":"Supplier added successfully.");render()}}
function expenseModal(){openModal(`<div class="modal-head"><h3>Add Expense</h3><button class="close" onclick="closeModal()">×</button></div><form id="expenseForm"><div class="form-grid"><div class="field"><label>Date</label><input name="date" type="date" value="${today()}" required></div><div class="field"><label>Category</label><select name="category"><option>Advertising</option><option>Packaging</option><option>Transport</option><option>Office</option><option>Other</option></select></div><div class="field"><label>Amount</label><input name="amount" type="number" step=".01" required></div><div class="field"><label>Note</label><input name="note"></div></div><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Cancel</button><button class="btn primary">Save Expense</button></div></form>`);document.getElementById("expenseForm").onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));d.amount=+d.amount;db.expenses.push({id:id("EXP"),...d});save();closeModal();toast("Expense added successfully.");render()}}
function paymentModal(){openModal(`<div class="modal-head"><h3>Supplier Payment</h3><button class="close" onclick="closeModal()">×</button></div><form id="paymentForm"><div class="form-grid"><div class="field"><label>Date</label><input name="date" type="date" value="${today()}"></div><div class="field"><label>Supplier</label><select name="supplierId">${suppliersOptions()}</select></div><div class="field"><label>Method</label><select name="method"><option>bKash</option><option>Nagad</option><option>Bank</option></select></div><div class="field"><label>Amount</label><input name="amount" type="number" step=".01" required></div><div class="field fullrow"><label>Note</label><input name="note"></div></div><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Cancel</button><button class="btn primary">Save Payment</button></div></form>`);document.getElementById("paymentForm").onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));d.amount=+d.amount;db.payments.push({id:id("PAY"),...d});save();closeModal();toast("Supplier payment added successfully.");render()}}
function accountModal(){openModal(`<div class="modal-head"><h3>My Payment Account</h3><button class="close" onclick="closeModal()">×</button></div><form id="accountForm"><div class="form-grid"><div class="field"><label>Type</label><select name="type"><option>Bank</option><option>bKash</option><option>Nagad</option></select></div><div class="field"><label>Number / Account</label><input name="number" required></div><div class="field fullrow"><label>Account Name</label><input name="name"></div></div><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Cancel</button><button class="btn primary">Save Account</button></div></form>`);document.getElementById("accountForm").onsubmit=e=>{e.preventDefault();db.accounts.push({id:id("ACC"),...Object.fromEntries(new FormData(e.target))});save();closeModal();toast("Payment account added successfully.");render()}}
function viewOrder(oid){let o=db.orders.find(x=>x.id===oid);openModal(`<div class="modal-head"><div><h3>Order ${esc(o.id)}</h3><div class="muted">${esc(o.date)} • ${esc(o.source)}</div></div><button class="close" onclick="closeModal()">×</button></div><div class="summary"><div><small>Customer</small><strong>${esc(o.customerName)}</strong></div><div><small>Sales</small><strong>${money(sales(o))}</strong></div><div><small>Profit</small><strong>${money(profit(o))}</strong></div><div><small>Status</small><strong>${badge(o.status)}</strong></div></div><p><b>Phone:</b> ${esc(o.phone)}<br><b>Address:</b> ${esc(o.address)}<br><b>Product:</b> ${esc(o.productName)} × ${o.quantity}<br><b>Courier:</b> ${esc(o.courier)}<br><b>Tracking:</b> ${o.trackingLink?`<a href="${esc(o.trackingLink)}" target="_blank">Open</a>`:"-"}</p><div class="modal-actions"><button class="btn" onclick="closeModal()">Close</button><button class="btn" onclick="orderEdit('${o.id}')">Edit</button></div>`)}
function orderEdit(idv){let o=db.orders.find(x=>x.id===idv);closeModal();orderModal(o)}
function customerView(cid){let c=db.customers.find(x=>x.id===cid),os=db.orders.filter(x=>x.customerId===cid);openModal(`<div class="modal-head"><div><h3>${esc(c.name)}</h3><div class="muted">${esc(c.phone)}</div></div><button class="close" onclick="closeModal()">×</button></div><p>${esc(c.address||"")}</p>${os.length?orderTable(os):empty("No history.")}<div class="modal-actions"><button class="btn" onclick="closeModal()">Close</button></div>`)}
function customerEdit(cid){let c=db.customers.find(x=>x.id===cid),o=db.orders.find(x=>x.customerId===cid);closeModal();orderModal(o||{id:id("ORD"),date:today(),customerId:cid,customerName:c.name,phone:c.phone,address:c.address,source:"Marketplace",status:"Pending",quantity:1})}
function customerDelete(cid){if(confirm("Delete customer and all their orders?")){db.orders=db.orders.filter(x=>x.customerId!==cid);db.customers=db.customers.filter(x=>x.id!==cid);save();toast("Customer deleted.");render()}}
function productDelete(pid){if(confirm("Delete this product?")){db.products=db.products.filter(x=>x.id!==pid);save();toast("Product deleted.");render()}}
function supplierDelete(sid){if(confirm("Delete this supplier?")){db.suppliers=db.suppliers.filter(x=>x.id!==sid);save();toast("Supplier deleted.");render()}}
function expenseDelete(eid){db.expenses=db.expenses.filter(x=>x.id!==eid);save();toast("Expense deleted.");render()}
function saveSettings(){db.settings.name=document.getElementById("sname").value;db.settings.currency=document.getElementById("scurrency").value;db.settings.notify=document.getElementById("toggle").classList.contains("on");save();toast("Settings saved.");render()}
function backup(){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:"application/json"}));a.download="al-furqun-erp-backup.json";a.click();URL.revokeObjectURL(a.href)}
function resetAll(){if(confirm("Delete all ERP data from this browser?")){localStorage.removeItem(KEY);db=read();toast("All local data reset.");render()}}
function filterRows(tableId,q){let t=document.getElementById(tableId);if(!t)return;q=q.toLowerCase().trim();t.querySelectorAll("tbody tr").forEach(r=>r.style.display=(!q||r.dataset.search.includes(q))?"":"none")}
function bind(){nav();document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{page=b.dataset.page;render();document.getElementById("sidebar").classList.remove("open")})}
document.getElementById("loginForm").onsubmit=e=>{e.preventDefault();if(username.value==="admin"&&password.value==="1234"){sessionStorage.af=1;render()}else toast("Wrong username or password.",false)}
document.getElementById("logout").onclick=()=>{sessionStorage.removeItem("af");document.getElementById("app").classList.add("hidden");document.getElementById("login").classList.remove("hidden")}
document.getElementById("menu").onclick=()=>document.getElementById("sidebar").classList.toggle("open");
document.getElementById("search").oninput=e=>{if(page==="customers"||page==="products")render()}
if(sessionStorage.af==="1")render();

document.addEventListener("input",e=>{if(e.target.id==="customerSearch"||e.target.id==="productSearch"){document.getElementById("search").value=e.target.value;render()}});
